### ISSUE TITLE
'git lfs pull' not work

### ISSUE THREAD

**Issue by shichen-wang** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#10]
When I install face_detection with code: 'git lfs pull' in ‘tools/readme.md’.
My pycharm told me 'batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.'
How can I fix this.

**Comment by mpc001** [comment]
Hi, you can probably try again now. The quota should have been reset. If this still doesn't work, please let me know.

**Comment by shichen-wang** [comment]
Thanks for your attention. I have found another way to solve this question. The main goal of 'git lfs pull' is to download a weight file which named Resnet50_Final.pth. You can find it in https://github.com/biubug6/Pytorch_Retinaface. 
Download and put it in face_detection/ibug/face_detection/retina_face/weights/Resnet50_Final.pth.
Then enjoy your code. 
Hope it can help others.
