### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by epicwarhd** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#11]
Do you have any benchmark for inference time ? I have tried with 10-second-length video and it took about 1-2 minutes to print the result.

**Comment by mpc001** [comment]
Hi @epicwarhd, assuming that the LRS3 landmarks are ready, it takes ~20 minutes for inference on the LRS3 test set (50 minutes) on an NVIDIA A100 GPU.

**Comment by longkhanh-fam** [comment]
Hi @mpc001 , which one is used for the inference that you mention. The eval.py or the demo.py (notebook in colab)
