### ISSUE TITLE
There is something wrong in README

### ISSUE THREAD

**Issue by fengbaoyihao3000** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#12]
Mouth ROIs Cropping should use command "python crop_mouth.py" instead of "python main.py"(this is old one).

and it seems there is No module named 'ibug.face_detection' ?

**Comment by mpc001** [comment]
Hi @fengbaoyihao3000 Thanks for pointing out this and README has been fixed. `ibug.face_detection` is a third-party package for face detection. You can find instructions on how to install it at [tools](https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages/tree/master/tools) folder.
