### ISSUE TITLE
RetinaFace detector not work

### ISSUE THREAD

**Issue by SHAIIM04** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#16]
Thank you for releasing your code to the public, I faced issues when trying to apply crop_mouth.py using the RetinaFace detector while when using MediaPipe it works well!

<img width="1123" alt="Screenshot 2023-06-06 at 6 35 13 PM" src="https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages/assets/36881881/892f6231-5fac-4cee-90a9-db6d131b876c">

I have another Q, AVSRDataLoader(modality="video", speed_rate=1, transform=False, detector=cfg.detector, convert_gray=False) I applied it like this when I using MediaPipe detector, which means there is not any transform on frames! because I see  there are transforms on videos such as see below

<img width="1300" alt="Screenshot 2023-06-06 at 6 44 08 PM" src="https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages/assets/36881881/c051cf61-4837-4cc9-afdf-8652ecebbe43">

regards

**Comment by mpc001** [comment]
Hi @SHAIIM04 for the first question, it looks like the pretrained weight for face detector might not have loaded properly. Can you please try installing the `retinaface` face detector and `fan` face alignment libraries using the following steps? [link](https://github.com/mpc001/auto_avsr/tree/main/tools#option-2-install-by-using-compressed-files). For the second question, as retinaface is more precise and stable than mediapipe for preprocessing datasets, can you try retinaface instead?
