### ISSUE TITLE
Training Code Required

### ISSUE THREAD

**Issue by Fengdalu** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#3]
Thanks for the releasement. I wonder if the training code will be available in the future? Thanks.

**Comment by joyolee** [comment]
I would ask the same question, it will be great for the community if the training script of the baseline model can be available!

**Comment by yan159yan** [comment]
I would ask the same question..

**Comment by taylor2success** [comment]
I would ask the same question.

**Comment by hosythach** [comment]
I would ask the same question. I would like to create a repository like this myself.

**Comment by shercostiniano** [comment]
I would like to train this model in a low-resource language (Filipino), any updates or progress for the training code will be much appreciated. Looking forward to reaching out thru email or twitter.

**Comment by HBU-Lin-Li** [comment]
Hello,
I would ask the same question, it will be great for the community if the training script of the baseline model can be available!

**Comment by mpc001** [comment]
Hello everyone, we have released the training recipe for [Auto-AVSR](https://github.com/mpc001/auto_avsr). This recipe includes the code for VSR and ASR, and we will be releasing AV-ASR soon.
