### ISSUE TITLE
Fail to reproduce result from demo video

### ISSUE THREAD

**Issue by CompactSupport** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#5]
I tried to reproduce the result of the Mandarin lip reading from the following demo video:

https://youtu.be/FIau-6JA9Po?t=33

I've made a clip "demo_cn.mp4" from this video 0:33-0:41.

My code:

`python main.py --config-filename configs/CMLR_V_WER8.0.ini --data-filename inputs/demo_cn.mp4`

The output:

```
load a pre-trained model from: models/CMLR/CMLR_V_WER8.0/model.pth
face tracking speed: 4.90 fps.
hyp: 有一种种的人俗话说的大家人才能真的一年里的一个行
```

This is different from the one shown in the demo: 中青祝愿大家在新的一年里新春愉快身体健康

I also extracted mouth ROIs from the clip ([link](https://files.catbox.moe/r8k58y.avi)).

Would you please let me know if I missed anything?

**Comment by zhunge** [comment]
set your video fps=25, then you can get correct result

**Comment by mostafamdy** [comment]
same here. the visual only is not working well but the visual and audio are perfect.
