### ISSUE TITLE
Audio-Visual Speech Recognition Model

### ISSUE THREAD

**Issue by DaikiShimada** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#7]
hi,

Do you have plan to release code/model of audio-visual speech recognition model proposed in "[End-to-end Audio-visual Speech Recognition with Conformers](https://arxiv.org/abs/2102.06657)"?

Thanks!

**Comment by mpc001** [comment]
Hi @DaikiShimada, we have released code and model for its successor [Auto-AVSR: Audio-Visual Speech Recognition with Automatic Labels](https://arxiv.org/abs/2303.14307). Please feel free to check it.
